#{{{
#     Name: Monoplex
# Location: cmus/monoplex.theme
#   Author: Mihail Szabolcs <https://mihail.co>
#  Version: 1.0
#  License: Same as cmus itself.
#}}}

set color_cmdline_bg=default
set color_cmdline_fg=default
set color_cmdline_attr=default

set color_win_title_bg=235
set color_win_title_fg=250
set color_win_title_attr=default

set color_win_fg=default
set color_win_bg=default
set color_win_attr=default

set color_separator=default

set color_titleline_bg=250
set color_titleline_fg=235
set color_titleline_attr=default

set color_statusline_bg=237
set color_statusline_fg=145
set color_statusline_progress_bg=237
set color_statusline_progress_fg=145

set color_win_cur=130
set color_win_dir=130

set color_win_sel_bg=250
set color_win_sel_fg=235
set color_win_sel_attr=default

set color_win_inactive_sel_bg=default
set color_win_inactive_sel_fg=default
set color_win_inactive_sel_attr=default

set color_win_cur_sel_bg=250
set color_win_cur_sel_fg=235
set color_win_cur_sel_attr=default

set color_win_inactive_cur_sel_bg=default
set color_win_inactive_cur_sel_fg=130
set color_win_inactive_cur_sel_attr=default

set color_error=196
set color_info=default
