#!/bin/bash

USER_AGENT='Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5'
WEATHER_CACHE='/tmp/tmux-accuweather-cache'

if [ -z $WEATHER_CACHE_EXPIRE ]; then
	WEATHER_CACHE_EXPIRE=3600 # 1 hour
fi

if [ -z $WEATHER_URL ]; then
	WEATHER_URL='https://www.accuweather.com/en/ro/targu-mures/289415/weather-forecast/289415'
fi

function fetch()
{
	curl -s -A "$USER_AGENT" $WEATHER_URL | grep '<span class="large-temp">' | head -n 1 | grep -PZo '[0-9]+' > $WEATHER_CACHE
}

function is_cache_expired()
{
	if [ ! -f $WEATHER_CACHE ]; then
		return 1
	fi

	diff=$(($(date +%s) - $(date -r $WEATHER_CACHE +%s)))

	if [ $diff -gt $WEATHER_CACHE_EXPIRE ]; then
		return 1
	else
		return 0
	fi
}

is_cache_expired
if [ $? -eq 1 ]; then
	fetch
fi

cat $WEATHER_CACHE
exit 0
